roles:
  - 2363cc86-613f-437e-beae-015092c6e707
email: levi@pixelandhammer.com
first_name: Levi
last_name: McCurdy
id: 7c2de999-7141-4c05-ad64-8fcc093a8170
super: true
password_hash: $2y$10$kE1tkMPCt1pYqQb7yZ/Ny.NM2EdKuVoR5xBkCYYB.iovccNJ0OPSG
